# Generated by Django 4.2.7 on 2025-07-15 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paper_management', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考试名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='考试描述')),
                ('subject', models.CharField(max_length=50, verbose_name='科目')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration', models.IntegerField(verbose_name='考试时长(分钟)')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('in_progress', '进行中'), ('completed', '已结束'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paper_management.paper', verbose_name='试卷')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('submitted', '已提交'), ('marked', '已阅卷'), ('cancelled', '已取消')], default='not_started', max_length=20, verbose_name='状态')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='分数')),
                ('is_passed', models.BooleanField(blank=True, null=True, verbose_name='是否通过')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='exam_monitoring.exam', verbose_name='考试')),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '考试记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('enter', '进入考试'), ('leave', '离开考试'), ('submit', '提交答案'), ('change_answer', '修改答案'), ('switch_tab', '切换标签页'), ('full_screen_exit', '退出全屏'), ('copy_attempt', '尝试复制'), ('paste_attempt', '尝试粘贴'), ('print_attempt', '尝试打印'), ('face_missing', '人脸丢失'), ('multiple_faces', '多人脸检测'), ('unknown_face', '未知人脸'), ('other', '其他行为')], max_length=20, verbose_name='行为')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('details', models.TextField(blank=True, null=True, verbose_name='详细信息')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='exam_snapshots/%Y/%m/%d/', verbose_name='屏幕截图')),
                ('is_violation', models.BooleanField(default=False, verbose_name='是否违规')),
                ('exam_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='exam_monitoring.examrecord', verbose_name='考试记录')),
            ],
            options={
                'verbose_name': '考试快照',
                'verbose_name_plural': '考试快照',
                'ordering': ['exam_record', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考场名称')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='考场位置')),
                ('capacity', models.IntegerField(default=30, verbose_name='考场容量')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='exam_monitoring.exam', verbose_name='考试')),
                ('invigilators', models.ManyToManyField(related_name='invigilated_rooms', to=settings.AUTH_USER_MODEL, verbose_name='监考人员')),
            ],
            options={
                'verbose_name': '考场',
                'verbose_name_plural': '考场',
                'ordering': ['exam', 'name'],
                'unique_together': {('exam', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='座位号')),
                ('status', models.CharField(choices=[('registered', '已报名'), ('approved', '已审核'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='registered', max_length=20, verbose_name='状态')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_registrations', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='exam_monitoring.exam', verbose_name='考试')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='exam_monitoring.examroom', verbose_name='考场')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to=settings.AUTH_USER_MODEL, verbose_name='考生')),
            ],
            options={
                'verbose_name': '考试报名',
                'verbose_name_plural': '考试报名',
                'ordering': ['-registered_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.AddField(
            model_name='examrecord',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_record', to='exam_monitoring.examregistration', verbose_name='报名记录'),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL, verbose_name='考生'),
        ),
        migrations.CreateModel(
            name='ExamNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('system', '系统通知'), ('invigilator', '监考员通知'), ('warning', '警告通知'), ('info', '信息通知')], default='system', max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=100, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='exam_monitoring.exam', verbose_name='考试')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='exam_monitoring.examroom', verbose_name='考场')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_notifications', to=settings.AUTH_USER_MODEL, verbose_name='考生')),
            ],
            options={
                'verbose_name': '考试通知',
                'verbose_name_plural': '考试通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='examrecord',
            unique_together={('exam', 'student')},
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(verbose_name='题目ID')),
                ('answer_content', models.TextField(verbose_name='答案内容')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='是否正确')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='得分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exam_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam_monitoring.examrecord', verbose_name='考试记录')),
            ],
            options={
                'verbose_name': '考生答案',
                'verbose_name_plural': '考生答案',
                'ordering': ['exam_record', 'question_id'],
                'unique_together': {('exam_record', 'question_id')},
            },
        ),
    ]
