from rest_framework.test import APITestCase, APIClient
from rest_framework import status
from rest_framework.response import Response
from exam_monitoring.models import ExamSession
from typing import Any, Dict, Literal
from rest_framework.test import APITestCase, APIClient

class ExamAPITests(APITestCase):
    client: APIClient
    user: Any
    exam: ExamSession

    def setUp(self) -> None: ...
    def test_get_current_exam(self) -> None: ...
    def test_submit_exam(self) -> None: ...
    def test_monitor_exam(self) -> None: ...
    def test_websocket_connection(self) -> None: ...
    def test_anti_cheating_detection(self) -> None: ...