# Generated by Django 5.2.5 on 2025-08-20 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "用户登录"),
                            ("logout", "用户登出"),
                            ("create", "创建操作"),
                            ("update", "更新操作"),
                            ("delete", "删除操作"),
                            ("export", "导出操作"),
                            ("import", "导入操作"),
                            ("system", "系统事件"),
                            ("error", "错误日志"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="操作对象模型",
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="操作对象ID"
                    ),
                ),
                ("description", models.TextField(verbose_name="操作内容")),
                (
                    "status",
                    models.CharField(
                        default="success", max_length=20, verbose_name="操作结果"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="设备信息"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统日志",
                "verbose_name_plural": "系统日志",
                "ordering": ["-action_time"],
            },
        ),
    ]
