# Generated by Django 5.2.5 on 2025-08-20 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DifficultyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "简单"),
                            (2, "较简单"),
                            (3, "中等"),
                            (4, "较难"),
                            (5, "困难"),
                        ],
                        unique=True,
                        verbose_name="难度级别",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, verbose_name="描述"),
                ),
            ],
            options={
                "verbose_name": "难度级别",
                "verbose_name_plural": "难度级别",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="QuestionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("single_choice", "单选题"),
                            ("multiple_choice", "多选题"),
                            ("true_false", "判断题"),
                            ("fill_blank", "填空题"),
                            ("short_answer", "简答题"),
                            ("programming", "编程题"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="类型名称",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
            ],
            options={
                "verbose_name": "题目类型",
                "verbose_name_plural": "题目类型",
            },
        ),
        migrations.CreateModel(
            name="KnowledgePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="知识点名称")),
                ("subject", models.CharField(max_length=100, verbose_name="所属科目")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_knowledge_points",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="question_bank.knowledgepoint",
                        verbose_name="父级知识点",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识点",
                "verbose_name_plural": "知识点",
                "unique_together": {("name", "subject", "parent")},
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="题库名称")),
                ("subject", models.CharField(max_length=100, verbose_name="科目")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_question_banks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "题库",
                "verbose_name_plural": "题库",
                "ordering": ["-created_at"],
                "unique_together": {("name", "subject")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="题目内容")),
                ("answer", models.TextField(verbose_name="参考答案")),
                ("analysis", models.TextField(blank=True, verbose_name="解析")),
                (
                    "score",
                    models.PositiveSmallIntegerField(default=1, verbose_name="分值"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "difficulty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="question_bank.difficultylevel",
                        verbose_name="难度级别",
                    ),
                ),
                (
                    "knowledge_points",
                    models.ManyToManyField(
                        related_name="questions",
                        to="question_bank.knowledgepoint",
                        verbose_name="知识点",
                    ),
                ),
                (
                    "question_bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="question_bank.questionbank",
                        verbose_name="所属题库",
                    ),
                ),
                (
                    "question_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="question_bank.questiontype",
                        verbose_name="题目类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目",
                "verbose_name_plural": "题目",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="question_images/", verbose_name="图片"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="描述"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="question_bank.question",
                        verbose_name="所属题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目图片",
                "verbose_name_plural": "题目图片",
            },
        ),
        migrations.CreateModel(
            name="QuestionImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="question_imports/", verbose_name="导入文件"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "total_count",
                    models.PositiveIntegerField(default=0, verbose_name="总题目数"),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(default=0, verbose_name="成功导入数"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "question_bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="question_bank.questionbank",
                        verbose_name="目标题库",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目导入",
                "verbose_name_plural": "题目导入",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_key", models.CharField(max_length=10, verbose_name="选项键")),
                ("option_content", models.TextField(verbose_name="选项内容")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="是否正确答案"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="question_bank.question",
                        verbose_name="所属题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目选项",
                "verbose_name_plural": "题目选项",
                "ordering": ["option_key"],
                "unique_together": {("question", "option_key")},
            },
        ),
    ]
